CREATE DATABASE IF NOT EXISTS r310 CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE r310;

CREATE TABLE IF NOT EXISTS countries (
    code    CHAR(2)      NOT NULL PRIMARY KEY,
    name_us VARCHAR(100) NOT NULL,
    name_fr VARCHAR(100) NOT NULL,
    region  VARCHAR(50)
);

INSERT INTO countries (code, name_us, name_fr, region) VALUES
('AD','Andorra','Andorre','Europe'),
('AE','United Arab Emirates','Émirats arabes unis','Asia'),
('AF','Afghanistan','Afghanistan','Asia'),
('AG','Antigua and Barbuda','Antigua-et-Barbuda','Americas'),
('AL','Albania','Albanie','Europe'),
('AM','Armenia','Arménie','Asia'),
('AO','Angola','Angola','Africa'),
('AR','Argentina','Argentine','Americas'),
('AT','Austria','Autriche','Europe'),
('AU','Australia','Australie','Oceania'),
('AZ','Azerbaijan','Azerbaïdjan','Asia'),
('BA','Bosnia and Herzegovina','Bosnie-Herzégovine','Europe'),
('BB','Barbados','Barbade','Americas'),
('BD','Bangladesh','Bangladesh','Asia'),
('BE','Belgium','Belgique','Europe'),
('BF','Burkina Faso','Burkina Faso','Africa'),
('BG','Bulgaria','Bulgarie','Europe'),
('BH','Bahrain','Bahreïn','Asia'),
('BI','Burundi','Burundi','Africa'),
('BJ','Benin','Bénin','Africa'),
('BN','Brunei','Brunéi','Asia'),
('BO','Bolivia','Bolivie','Americas'),
('BR','Brazil','Brésil','Americas'),
('BS','Bahamas','Bahamas','Americas'),
('BT','Bhutan','Bhoutan','Asia'),
('BW','Botswana','Botswana','Africa'),
('BY','Belarus','Bélarus','Europe'),
('BZ','Belize','Belize','Americas'),
('CA','Canada','Canada','Americas'),
('CD','Congo DR','Congo RD','Africa'),
('CF','Central African Republic','République centrafricaine','Africa'),
('CG','Congo Republic','Congo République','Africa'),
('CH','Switzerland','Suisse','Europe'),
('CI','Ivory Coast','Côte d Ivoire','Africa'),
('CL','Chile','Chili','Americas'),
('CM','Cameroon','Cameroun','Africa'),
('CN','China','Chine','Asia'),
('CO','Colombia','Colombie','Americas'),
('CR','Costa Rica','Costa Rica','Americas'),
('CU','Cuba','Cuba','Americas'),
('CV','Cape Verde','Cap-Vert','Africa'),
('CY','Cyprus','Chypre','Europe'),
('CZ','Czech Republic','République tchèque','Europe'),
('DE','Germany','Allemagne','Europe'),
('DJ','Djibouti','Djibouti','Africa'),
('DK','Denmark','Danemark','Europe'),
('DM','Dominica','Dominique','Americas'),
('DZ','Algeria','Algérie','Africa'),
('EC','Ecuador','Équateur','Americas'),
('EE','Estonia','Estonie','Europe'),
('EG','Egypt','Égypte','Africa'),
('ER','Eritrea','Érythrée','Africa'),
('ES','Spain','Espagne','Europe'),
('ET','Ethiopia','Éthiopie','Africa'),
('FI','Finland','Finlande','Europe'),
('FJ','Fiji','Fidji','Oceania'),
('FR','France','France','Europe'),
('GA','Gabon','Gabon','Africa'),
('GB','United Kingdom','Royaume-Uni','Europe'),
('GE','Georgia','Géorgie','Asia'),
('GH','Ghana','Ghana','Africa'),
('GM','Gambia','Gambie','Africa'),
('GN','Guinea','Guinée','Africa'),
('GQ','Equatorial Guinea','Guinée équatoriale','Africa'),
('GR','Greece','Grèce','Europe'),
('GT','Guatemala','Guatemala','Americas'),
('GW','Guinea-Bissau','Guinée-Bissau','Africa'),
('GY','Guyana','Guyana','Americas'),
('HN','Honduras','Honduras','Americas'),
('HR','Croatia','Croatie','Europe'),
('HT','Haiti','Haïti','Americas'),
('HU','Hungary','Hongrie','Europe'),
('ID','Indonesia','Indonésie','Asia'),
('IE','Ireland','Irlande','Europe'),
('IL','Israel','Israël','Asia'),
('IN','India','Inde','Asia'),
('IQ','Iraq','Irak','Asia'),
('IR','Iran','Iran','Asia'),
('IS','Iceland','Islande','Europe'),
('IT','Italy','Italie','Europe'),
('JM','Jamaica','Jamaïque','Americas'),
('JO','Jordan','Jordanie','Asia'),
('JP','Japan','Japon','Asia'),
('KE','Kenya','Kenya','Africa'),
('KG','Kyrgyzstan','Kirghizistan','Asia'),
('KH','Cambodia','Cambodge','Asia'),
('KI','Kiribati','Kiribati','Oceania'),
('KM','Comoros','Comores','Africa'),
('KN','Saint Kitts and Nevis','Saint-Kitts-et-Nevis','Americas'),
('KP','North Korea','Corée du Nord','Asia'),
('KR','South Korea','Corée du Sud','Asia'),
('KW','Kuwait','Koweït','Asia'),
('KZ','Kazakhstan','Kazakhstan','Asia'),
('LA','Laos','Laos','Asia'),
('LB','Lebanon','Liban','Asia'),
('LC','Saint Lucia','Sainte-Lucie','Americas'),
('LI','Liechtenstein','Liechtenstein','Europe'),
('LK','Sri Lanka','Sri Lanka','Asia'),
('LR','Liberia','Libéria','Africa'),
('LS','Lesotho','Lesotho','Africa'),
('LT','Lithuania','Lituanie','Europe'),
('LU','Luxembourg','Luxembourg','Europe'),
('LV','Latvia','Lettonie','Europe'),
('LY','Libya','Libye','Africa'),
('MA','Morocco','Maroc','Africa'),
('MC','Monaco','Monaco','Europe'),
('MD','Moldova','Moldavie','Europe'),
('ME','Montenegro','Monténégro','Europe'),
('MG','Madagascar','Madagascar','Africa'),
('MH','Marshall Islands','Îles Marshall','Oceania'),
('MK','North Macedonia','Macédoine du Nord','Europe'),
('ML','Mali','Mali','Africa'),
('MM','Myanmar','Myanmar','Asia'),
('MN','Mongolia','Mongolie','Asia'),
('MR','Mauritania','Mauritanie','Africa'),
('MT','Malta','Malte','Europe'),
('MU','Mauritius','Maurice','Africa'),
('MV','Maldives','Maldives','Asia'),
('MW','Malawi','Malawi','Africa'),
('MX','Mexico','Mexique','Americas'),
('MY','Malaysia','Malaisie','Asia'),
('MZ','Mozambique','Mozambique','Africa'),
('NA','Namibia','Namibie','Africa'),
('NE','Niger','Niger','Africa'),
('NG','Nigeria','Nigeria','Africa'),
('NI','Nicaragua','Nicaragua','Americas'),
('NL','Netherlands','Pays-Bas','Europe'),
('NO','Norway','Norvège','Europe'),
('NP','Nepal','Népal','Asia'),
('NR','Nauru','Nauru','Oceania'),
('NZ','New Zealand','Nouvelle-Zélande','Oceania'),
('OM','Oman','Oman','Asia'),
('PA','Panama','Panama','Americas'),
('PE','Peru','Pérou','Americas'),
('PG','Papua New Guinea','Papouasie-Nouvelle-Guinée','Oceania'),
('PH','Philippines','Philippines','Asia'),
('PK','Pakistan','Pakistan','Asia'),
('PL','Poland','Pologne','Europe'),
('PT','Portugal','Portugal','Europe'),
('PW','Palau','Palaos','Oceania'),
('PY','Paraguay','Paraguay','Americas'),
('QA','Qatar','Qatar','Asia'),
('RO','Romania','Roumanie','Europe'),
('RS','Serbia','Serbie','Europe'),
('RU','Russia','Russie','Europe'),
('RW','Rwanda','Rwanda','Africa'),
('SA','Saudi Arabia','Arabie saoudite','Asia'),
('SB','Solomon Islands','Îles Salomon','Oceania'),
('SC','Seychelles','Seychelles','Africa'),
('SD','Sudan','Soudan','Africa'),
('SE','Sweden','Suède','Europe'),
('SG','Singapore','Singapour','Asia'),
('SI','Slovenia','Slovénie','Europe'),
('SK','Slovakia','Slovaquie','Europe'),
('SL','Sierra Leone','Sierra Leone','Africa'),
('SM','San Marino','Saint-Marin','Europe'),
('SN','Senegal','Sénégal','Africa'),
('SO','Somalia','Somalie','Africa'),
('SR','Suriname','Suriname','Americas'),
('SS','South Sudan','Soudan du Sud','Africa'),
('ST','São Tomé and Príncipe','Sao Tomé-et-Principe','Africa'),
('SV','El Salvador','El Salvador','Americas'),
('SY','Syria','Syrie','Asia'),
('SZ','Eswatini','Eswatini','Africa'),
('TD','Chad','Tchad','Africa'),
('TG','Togo','Togo','Africa'),
('TH','Thailand','Thaïlande','Asia'),
('TJ','Tajikistan','Tadjikistan','Asia'),
('TL','East Timor','Timor oriental','Asia'),
('TM','Turkmenistan','Turkménistan','Asia'),
('TN','Tunisia','Tunisie','Africa'),
('TO','Tonga','Tonga','Oceania'),
('TR','Turkey','Turquie','Asia'),
('TT','Trinidad and Tobago','Trinité-et-Tobago','Americas'),
('TV','Tuvalu','Tuvalu','Oceania'),
('TZ','Tanzania','Tanzanie','Africa'),
('UA','Ukraine','Ukraine','Europe'),
('UG','Uganda','Ouganda','Africa'),
('US','United States','États-Unis','Americas'),
('UY','Uruguay','Uruguay','Americas'),
('UZ','Uzbekistan','Ouzbékistan','Asia'),
('VA','Vatican City','Vatican','Europe'),
('VC','Saint Vincent and the Grenadines','Saint-Vincent-et-les-Grenadines','Americas'),
('VE','Venezuela','Venezuela','Americas'),
('VN','Vietnam','Viêt Nam','Asia'),
('VU','Vanuatu','Vanuatu','Oceania'),
('WS','Samoa','Samoa','Oceania'),
('YE','Yemen','Yémen','Asia'),
('ZA','South Africa','Afrique du Sud','Africa'),
('ZM','Zambia','Zambie','Africa'),
('ZW','Zimbabwe','Zimbabwe','Africa')
ON DUPLICATE KEY UPDATE
    name_us = VALUES(name_us),
    name_fr = VALUES(name_fr),
    region  = VALUES(region);
